Crux-app/crux/auftrag/urls.py
from django.urls import path

from . import views

app_name = 'auftrag'
urlpatterns = [
    # AUFTRAG URLS
    path('', views.index, name='auftrag_index'),
    path('updated/<int:record_id>', views.update_order, name='update_auftrag'),
]

Crux-app/crux/bestellung/urls.py
from django.urls import path

from . import views

app_name = 'bestellung'
urlpatterns = [
    # ex: bestellung/
    path('', views.index, name='bestellung_index'),
    path('updated/<int:record_id>', views.update_order, name='update_bestellung'),
    path('new_order/', views.create_order, name='add_bestellung'),
    path('new_collective_order/', views.create_collective_order, name='add_sammelbestellung'),
]

Crux-app/crux/crux/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url,include


urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    # path('homepage/', include('homepage.urls', namespace='homepage')),
    path('textdocs/', include('textdocs.urls')),
    path('maschinenplanung/', include('maschinenplanung.urls', namespace='maschinenplanung')),
    path('bestellung/', include('bestellung.urls', namespace='bestellung')),
    path('auftrag/', include('auftrag.urls', namespace='auftrag')),
    path('produktionsauftrag/', include('produktionsauftrag.urls', namespace='produktionsauftrag')),
    path('lieferschein/', include('lieferschein.urls', namespace='lieferschein')),
    path('rechnung/', include('rechnung.urls', namespace='rechnung')),
    path('aktuelles/', include('aktuelles.urls')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('admin/', admin.site.urls),
]

Crux-app/crux/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('login_user/', views.login_user, name='login_user'),
]

Crux-app/crux/rechnung/urls.py
from django.urls import path

from . import views

app_name = 'rechnung'
urlpatterns = [
    # AUFTRAG URLS
    path('', views.index, name='rechnung_index'),
    path('updated/<int:record_id>', views.update_order, name='update_rechnung'),
    path('generated/<int:record_id>', views.generate_invoice, name='generate_invoice'),
]

Crux-app/crux/stock/urls.py
from django.urls import path

from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.index, name='stock_index'),
    path('articles/', views.artikel, name='stock_articles'),
    path('materials/', views.material, name='stock_materials'),
    path('machines/', views.maschinen, name='stock_machines'),
    path('customers/', views.kunden, name='stock_customers'),
]

Crux-app/crux/homepage/models.py
from django.db import models

# Create your models here.

Crux-app/crux/homepage/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Crux-app/crux/homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import logout

import datetime


# Create your views here.

def index(request):
    dt = datetime.datetime.now()
    aktuelle_kw = dt.isocalendar()[1]
    aktuelle_kw_string = "KW " + str(aktuelle_kw)

    return render(request, 'homepage/index.html', {'aktuelle_kw_string': aktuelle_kw_string})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'homepage/index.html')
            else:
                return render(request, 'homepage/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'homepage/login.html', {'error_message': 'Invalid login'})
    return render(request, 'homepage/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'homepage/login.html', context)

class UserFormView(View):
    form_class = UserForm
    template_name = 'homepage/registration_form.html'

    # fill user info
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


    # submit user info to db
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('index')

        return render(request, self.template_name, {'form': form})



Crux-app/crux/homepage/templates/homepage/base.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Crux{% endblock %}</title>
  {% load staticfiles %}
  <script src="{% static 'homepage/scripts.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<!--  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!--  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->
<!--  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}">
  {% block head %}
  {% endblock %}
</head>

{% block style %}
{% endblock %}

<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">

    <!-- Header -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:index' %}">Crux</a>
    </div>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Suche</button>
    </form>

    {% block navbutton %}
    {% endblock %}

    <ul class="nav navbar-nav navbar-right">
      <li>
        <a type="button" class="btn btn-dark btn-sm" href="logout_user/"> Logout
        </a>
      </li>
     </ul>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>

Crux-app/crux/homepage/templates/homepage/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Crux{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage:index' %}">Crux</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'homepage:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'homepage:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Crux-app/crux/homepage/templates/homepage/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Crux-app/crux/homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}

{% load staticfiles %}

{% block body %}

<div class="container-fluid" style="height: 100%">
  <div class="row" style="height: 100%">
    <div class="col-2 h-100">
      <div class="accordion" id="accordionExample">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <b>Lager</b>
              </button>
            </h2>
          </div>

          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'stock:stock_index' %})">Übersicht</a>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <b>Abläufe</b>
              </button>
            </h2>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          <a href="/aktuelles/" type="button" class="btn btn-secondary btn-lg btn-block">Aktuelles</a>
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'bestellung:bestellung_index' %})">Bestellung</a>
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'auftrag:auftrag_index' %})">Auftrag</a>
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'produktionsauftrag:produktionsauftrag_index' %})">Produktion</a>
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'lieferschein:lieferschein_index' %})">Lieferschein</a>
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'rechnung:rechnung_index' %})">Rechnung</a>

        </div>
      </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <b>Maschinenplanung</b>
              </button>
            </h2>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
        <div class="card-body">
          <a type="button" class="btn btn-light btn-lg btn-block" data-target="content" onclick="load_frame({% url 'maschinenplanung:maschinenplanung_index' %})">MP Ansicht</a>
        </div>
      </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingFour">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                <b>Auswertungen</b>
              </button>
            </h2>
          </div>
          <div id="collapseFour" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
              <a href="/maschinenplanung/" type="button" class="btn btn-light btn-lg btn-block">Rechnungen</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-9 embed-responsive">
      <iframe id="content">
        Your browser doesn't support iFrames.
      </iframe>
    </div>
    <div class="col-1">
      <h2 align="right"><span class="badge badge-dark">{{ aktuelle_kw_string }}</span></h2>
    </div>
  </div>
</div>

{% endblock %}

Crux-app/crux/homepage/templates/homepage/login.html
{% extends 'homepage/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'homepage:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'homepage:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Crux-app/crux/homepage/templates/homepage/registration_form.html
{% extends 'homepage/base.html' %}

{% block title %}Neuer Benutzer{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Neuen Benutzer erstellen</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'homepage/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Erstellen</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Wie erstelle ich einen Auftrag ?</h3>
                    <ul>
                        <li>Wählen Sie einen Artikel aus der Liste.</li>
                        <li>Falls nicht vorhanden. Erstellen Sie einen neuen Artikel im Lager.</li>
                        <li>Füllen Sie die restlichen Felder aus.</li>
                        <li>Datum Format: %Jahr-%Monat-%Tag.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}