Crux-app/crux/crux/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url,include


urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    # path('homepage/', include('homepage.urls', namespace='homepage')),
    path('textdocs/', include('textdocs.urls')),
    path('maschinenplanung/', include('maschinenplanung.urls', namespace='maschinenplanung')),
    path('bestellung/', include('bestellung.urls', namespace='bestellung')),
    path('auftrag/', include('auftrag.urls', namespace='auftrag')),
    path('produktionsauftrag/', include('produktionsauftrag.urls', namespace='produktionsauftrag')),
    path('lieferschein/', include('lieferschein.urls', namespace='lieferschein')),
    path('rechnung/', include('rechnung.urls', namespace='rechnung')),
    path('aktuelles/', include('aktuelles.urls')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('admin/', admin.site.urls),
]

Crux-app/crux/rechnung/urls.py
from django.urls import path

from . import views

app_name = 'rechnung'
urlpatterns = [
    # AUFTRAG URLS
    path('', views.index, name='rechnung_index'),
    path('updated/<int:record_id>', views.update_order, name='update_rechnung'),
    path('generated/<int:record_id>', views.generate_invoice, name='generate_invoice'),
]

Crux-app/crux/rechnung/models.py
from django.db import models

# Create your models here.

Crux-app/crux/rechnung/views.py
from django.shortcuts import render
from django_tables2 import RequestConfig
from bestellung.models import Order
from .tables import OrderTable
from django.shortcuts import redirect

# Create your views here.

def index(request):
    """index view is a table showing all orders"""
    table_single = OrderTable(Order.objects.filter(order_status="Rechnung", collection=False))
    table_collection = OrderTable(Order.objects.filter(order_status="Rechnung", collection=True))
    RequestConfig(request).configure(table_single)
    context = {
        'table_single': table_single,
        'table_collection': table_collection,
    }
    return render(request, 'rechnung/index.html', context)

def update_order(request, record_id):
    """update_order pushes via order_status from order up to invoice"""
    obj = Order.objects.get(pk=record_id)
    obj.order_status = 'Done'
    obj.save()
    print('item updated: ' + str(record_id))
    response = redirect('/rechnung/')
    return response

def generate_invoice(request, record_id):
    """generates invoice via pk """
    rechnung = Order.objects.get(pk=record_id)
    customer = rechnung.customer
    #customer is a foreignkey
    preis = rechnung.article.price_per_piece*rechnung.amount
    print(rechnung.article.price_per_piece)
    # print(customer.city)
    context = {
        'rechnung': rechnung,
        'customer': customer,
        'preis': preis,
    }
    return render(request, 'textdocs/invoice.html', context)

Crux-app/crux/rechnung/templates/rechnung/checkbox.html
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
  </div>

Crux-app/crux/rechnung/templates/rechnung/index.html
{% extends 'bestellung/base.html' %}

{% load render_table from django_tables2 %}

{% block app_name %}
Rechnungen
{% endblock %}

{% block body %}

<main class="content">

    {% render_table table_single %}

</main>
<div class="button" align="right">
    <a class="btn btn-outline-info btn-lg" href="#">Rechnung Erzeugen</a>
</div>
{% endblock %}

Crux-app/crux/rechnung/templates/rechnung/next_button.html
<div class="btn-group">
  <a class="btn btn-outline-info btn-sm" href="{% url 'rechnung:update_rechnung' record.id %}">Überführen</a>
  <a class="btn btn-outline-info btn-sm" href="{% url 'rechnung:generate_invoice' record.id %}">Anzeigen</a>
</div>