Crux-app/crux/bestellung/urls.py
from django.urls import path

from . import views

app_name = 'bestellung'
urlpatterns = [
    # ex: bestellung/
    path('', views.index, name='bestellung_index'),
    path('updated/<int:record_id>', views.update_order, name='update_bestellung'),
    path('new_order/', views.create_order, name='add_bestellung'),
    path('new_collective_order/', views.create_collective_order, name='add_sammelbestellung'),
]

Crux-app/crux/crux/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url,include


urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    # path('homepage/', include('homepage.urls', namespace='homepage')),
    path('textdocs/', include('textdocs.urls')),
    path('maschinenplanung/', include('maschinenplanung.urls', namespace='maschinenplanung')),
    path('bestellung/', include('bestellung.urls', namespace='bestellung')),
    path('auftrag/', include('auftrag.urls', namespace='auftrag')),
    path('produktionsauftrag/', include('produktionsauftrag.urls', namespace='produktionsauftrag')),
    path('lieferschein/', include('lieferschein.urls', namespace='lieferschein')),
    path('rechnung/', include('rechnung.urls', namespace='rechnung')),
    path('aktuelles/', include('aktuelles.urls')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('admin/', admin.site.urls),
]

Crux-app/crux/bestellung/models.py
from django.db import models
import datetime
from django.urls import reverse
from django import forms
from stock.models import Nummernkreise, Customer, Article

# Create your models here.
DEFAULT_CUSTOMER_ID = 1
class Order(models.Model):
    collection = models.BooleanField(("Sammelbestellung"), default=False)
    collection_name = models.CharField(("Bestellungsname"), max_length=250, default="Single")
    order_number_int = models.BigIntegerField(("Bestellnummer intern"), default=0)
    order_number_ext = models.BigIntegerField(("Bestellnummer extern"), default=0)
    article = models.ForeignKey('stock.Article', on_delete=models.CASCADE, verbose_name='Artikel')
    customer = models.ForeignKey('stock.Customer', on_delete=models.CASCADE, default=DEFAULT_CUSTOMER_ID, verbose_name='Kunde')
    amount = models.BigIntegerField(("Menge"), default=0)
    order_date = models.DateTimeField(("Bestelldatum"), default=datetime.datetime.today)
    delivery_date = models.DateTimeField(("Lieferdatum"), default=datetime.datetime.today)
    # production_starting_time = models.TimeField(("Startzeit"), default=datetime.datetime)
    order_status = models.CharField(("Status"), max_length=250, default="Bestellung")
    stock_amount = models.BigIntegerField(("Lagermenge"), default=0)

    def get_absolute_url(self):
        return reverse('bestellung_index')

    def __str__(self):
        return self.article.name + ' | ' + str(self.order_status) + ' | ' + str(self.customer)


# class CollectiveOrder(models.Model):
#     collection_name = models.CharField(max_length=250, default="Bestellung")
#     article_ids = models.ForeignKey('stock.Article', on_delete=models.CASCADE)
#     company = models.CharField(("Firma"), max_length=250)
#     amount = models.BigIntegerField(("Menge"))
#     order_date = models.DateField(("Bestelldatum"), default=datetime.date.today)
#     delivery_date = models.DateField(("Lieferdatum"), default=datetime.date.today)
#     order_status = models.CharField(max_length=250, default="Bestellung")
#
#     def get_absolute_url(self):
#         return reverse('bestellung_index')
#
#     def __str__(self):
#         return self.article.name + ' | ' + str(self.amount) + ' | ' + str(self.customer)

Crux-app/crux/bestellung/forms.py
from django import forms
from stock.models import Nummernkreise

from .models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['order_number_ext', 'article', 'customer', 'amount', 'order_date', 'delivery_date']


class CollectiveOrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['order_number_ext', 'collection_name', 'customer', 'order_date', 'article', 'amount', 'delivery_date']

Crux-app/crux/bestellung/views.py
from django.shortcuts import render
from django_tables2 import RequestConfig
from .models import Order
from stock.models import Nummernkreise
from .tables import OrderTable
from django.shortcuts import redirect
from .forms import OrderForm, CollectiveOrderForm


from django.views.generic.edit import CreateView, UpdateView, DeleteView


# gets table data and displays it
def index(request):
    """index view is a table showing all orders"""
    table_single = OrderTable(Order.objects.filter(order_status="Bestellung", collection=False))
    table_collection = OrderTable(Order.objects.filter(order_status="Bestellung", collection=True))
    RequestConfig(request).configure(table_single)
    context = {
        'table_single': table_single,
        'table_collection': table_collection,
    }
    return render(request, 'bestellung/index.html', context)

# gets record_id from the table to update corresponding object/obj.order_status and take it to the next lvl
# afterwards page refresh
def update_order(request, record_id):
    """update orders order_status überführt von einer Stufe zur nächsten"""
    obj = Order.objects.get(pk=record_id)
    obj.order_status = 'Auftrag'
    obj.save()
    print('item updated: ' + str(record_id))
    response = redirect('/bestellung/')
    return response

def create_order(request):
    """create a single new order"""
    form = OrderForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        order = form.save(commit=False)

        # this gets the order_number from DB, increment and save
        # db_number = Nummernkreise.objects.values_list('order_number', flat=True).get(pk=1)

        obj = Nummernkreise.objects.get(pk=1)
        obj.order_number +=1
        order.order_number_int = obj.order_number
        print(order)

        order.save()
        obj.save()

        response = redirect('/bestellung/')
        return response

    context = {
        "form": form,
    }
    print(context)
    return render(request, 'bestellung/order_form.html', context)

def create_collective_order(request):
    """create multiple orders that should refer to the same name"""
    form = CollectiveOrderForm(request.POST or None, request.FILES or None)
    print(CollectiveOrderForm)
    print(type(CollectiveOrderForm))
    if form.is_valid():
        print("FORM STARTS")
        for key in request.POST:
            print(key + "=")
            value = request.POST[key]
            print(value)
        print("FORM ENDS")


        order = form.save(commit=False)
        # print(order)

        # this gets the order_number from DB, increment and save
        # db_number = Nummernkreise.objects.values_list('order_number', flat=True).get(pk=1)

        # obj = Nummernkreise.objects.get(pk=1)
        # obj.order_number +=1
        # order.order_number_int = obj.order_number

        # order.save()
        # obj.save()

        response = redirect('/bestellung/new_collective_order/')
        return response

    context = {
        "form": form,
        # "form2": form2
    }
    return render(request, 'bestellung/collective_order_form.html', context)

# def create_album(request):
#     if not request.user.is_authenticated():
#         return render(request, 'music/login.html')
#     else:
#         form = OrderForm(request.POST or None, request.FILES or None)
#         if form.is_valid():
#             album = form.save(commit=False)
#             album.user = request.user
#             album.album_logo = request.FILES['album_logo']
#             file_type = album.album_logo.url.split('.')[-1]
#             file_type = file_type.lower()
#             if file_type not in IMAGE_FILE_TYPES:
#                 context = {
#                     'album': album,
#                     'form': form,
#                     'error_message': 'Image file must be PNG, JPG, or JPEG',
#                 }
#                 return render(request, 'music/create_album.html', context)
#             album.save()
#             return render(request, 'music/detail.html', {'album': album})
#         context = {
#             "form": form,
#         }
#         return render(request, 'music/create_album.html', context)

Crux-app/crux/bestellung/templates/bestellung/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Crux{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bestellung/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<style>

{% block style %}
{% endblock %}

</style>

<body>

<h2><span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; {% block app_name %}{% endblock %}</span></h2>

{% block body %}

{% endblock %}

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <li><a href="{% url 'bestellung:add_bestellung' %}">Einzelbestellung</a></li>
  <li><a href="{% url 'bestellung:add_sammelbestellung' %}">Sammelbestellung</a></li>
</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

</body>
</html>

Crux-app/crux/bestellung/templates/bestellung/check.html
<div class="chat-popup" id="myForm">
  <form action="/action_page.php" class="form-container">
    <h1>Chat</h1>

    <label for="msg"><b>Message</b></label>
    <textarea placeholder="Type message.." name="msg" required><textarea>

    <button type="submit" class="btn">Send</button>
    <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
  </form>
</div>

Crux-app/crux/bestellung/templates/bestellung/collective_order_form.html
{% load render_table from django_tables2 %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Eine neue Sammelbestellung eingeben</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bestellung/form_template3.html' %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Erstellen</button>
                        </div>
                         <div class="form-group">
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Wie erstelle ich einen Auftrag ?</h3>
                    <ul>
                        <li>Wählen Sie einen Artikel aus der Liste.</li>
                        <li>Falls nicht vorhanden. Erstellen Sie einen neuen Artikel im Lager.</li>
                        <li>Füllen Sie die restlichen Felder aus.</li>
                        <li>Datum Format: %Jahr-%Monat-%Tag.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>



{% endblock %}

Crux-app/crux/bestellung/templates/bestellung/form_template.html
  <div class="card-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="card">
      <div class="card-heading" role="tab" id="headingOne">
        <h4 class="card-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Einzelbestellungen
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="collapse-off" data-parent="#accordion">
        <div class="card-body">


  {% for field in form %}
          <div class="form-group mb-3">
<!--            <div class="col-sm-offset-2 col-sm-10">-->
<!--              <span class="text-danger small">{{ field.errors }}</span>-->
<!--            </div>-->
<!--            <span class="input-group-text">{{ field.label_tag }}</span>-->
<!--            <input type="text" class="form-control">{{ field }}-->
<!--          </div>-->

            <label for='{{ field.label_tag }}'>{{ field.label_tag }}</label>
            <div type="text" id='{{ field.label_tag }}'>{{ field }}</div>
          </div>

  {% endfor %}

          </div>
      </div>
    </div>
  </div>

Crux-app/crux/bestellung/templates/bestellung/form_template2.html
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Einzelbestellungen
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
        </div>
      </div>
    </div>
  </div>

Crux-app/crux/bestellung/templates/bestellung/form_template3.html
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">

    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ form.order_number_ext.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ form.order_number_ext.label_tag }}</label>
        <div class="col-sm-10">{{ form.order_number_ext }}</div>

        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ form.collection_name.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ form.collection_name.label_tag }}</label>
        <div class="col-sm-10">{{ form.collection_name }}</div>

        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ form.customer.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ form.customer.label_tag }}</label>
        <div class="col-sm-10">{{ form.customer }}</div>

        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ form.order_date.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ form.order_date.label_tag }}</label>
        <div class="col-sm-10">{{ form.order_date }}</div>

    </div>

      </div>
    </div>
    <div class="card">
      <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Aufträge</h3>
      <div class="card-body">
        <div id="table" form="form-horizontal">
          <span class="table-add float-right mb-3 mr-2"><a href="#!" class="text-success"><i class="fas fa-plus fa-2x"
                aria-hidden="true"></i></a></span>
          <table id="myTable" class="table table-sm table-bordered table-responsive-sm table-striped text-center">
            <tr>
                <th class="text-center">{{ form.article.label_tag }}</th>
                <th class="text-center">{{ form.amount.label_tag }}</th>
                <th class="text-center">{{ form.delivery_date.label_tag }}</th>
            </tr>
            <tr>
                <td id="Artikel" class="pt-3-half">{{ form.article }}</td>
                <td id="Menge" class="pt-3-half">{{ form.amount }}</td>
                <td id="Datum" class="pt-3-half">{{ form.delivery_date }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
      <button type="button" onclick="myFunction()">Neue Zeile</button>
  </div>
  </div>
    <script type="text/javascript">
function myFunction() {
  var table = document.getElementById("myTable");
  var row = table.insertRow(-1);
  var cell1html = document.getElementById("Artikel").innerHTML;
  var cell2html = document.getElementById("Menge").innerHTML;
  var cell3html = document.getElementById("Datum").innerHTML;
  var cell1 = row.insertCell(0);
  var cell2 = row.insertCell(1);
  var cell3 = row.insertCell(2);
  cell1.innerHTML = cell1html;
  cell2.innerHTML = cell2html;
  cell3.innerHTML = cell3html;
}
    </script>

Crux-app/crux/bestellung/templates/bestellung/index.html
{% extends 'bestellung/base.html' %}

{% load render_table from django_tables2 %}

{% block app_name %}
Bestellungen
{% endblock %}

{% block body %}

<main class="content">

    {% render_table table_single %}

</main>
{% endblock %}

Crux-app/crux/bestellung/templates/bestellung/next_button.html
<div>
  <a class="btn btn-info btn-sm" href="{% url 'bestellung:update_bestellung' record.id %}">Überführen</a>
  <a class="btn btn-info btn-sm" href="#">Anzeigen</a>
</div>

Crux-app/crux/bestellung/templates/bestellung/order_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% comment %}{% endcomment %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="card">
                <div class="card-body">
                    <h3>Eine neue Bestellung eingeben</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bestellung/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Erstellen</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="card">
                <div class="card-body">
                    <h3>Wie erstelle ich einen Auftrag ?</h3>
                    <ul>
                        <li>Wählen Sie einen Artikel aus der Liste.</li>
                        <li>Falls nicht vorhanden. Erstellen Sie einen neuen Artikel im Lager.</li>
                        <li>Füllen Sie die restlichen Felder aus.</li>
                        <li>Datum Format: %Jahr-%Monat-%Tag (Uhrzeit ist optional).</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}